const NOTIFICATION_TYPES = {
  REGISTER: "REGISTER",
  UPLOAD_CREDIT: "UPLOAD_CREDIT",
  NEW_QUEUE: "NEW_QUEUE",
  QUEUE_HAS_BEEN_STARTED: "QUEUE_HAS_BEEN_STARTED",
  QUEUE_HAS_BEEN_PAUSED: "QUEUE_HAS_BEEN_PAUSED",
  QUEUE_HAS_BEEN_FINISHED: "QUEUE_HAS_BEEN_FINISHED",
  QUEUE_HAS_BEEN_STARTED_AGAIN: "QUEUE_HAS_BEEN_STARTED_AGAIN",
  QUEUE_ERROR: "QUEUE_ERROR",
};

const NOTIFICATION_CHANNELS = {
  ALL: "ALL",
  WP: "WP",
  MAIL: "MAIL",
  NONE: "NONE",
};

const NOTIFICATION_STATUS = {
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  PENDING: "PENDING",
  IN_PROCESS: "IN_PROCESS",
};


module.exports = {NOTIFICATION_TYPES, NOTIFICATION_CHANNELS, NOTIFICATION_STATUS}